#Main equation made by Teivel, further changes by LiquidAmethyst

"""Definition, importation and objectification (possibly not actual words, but who cares!)"""

#Import
import time
import datetime

#Define variables.
x, powerTen = 1, 100000 		#The variable powerTen should be done by input, I leave that to you Eric.
n = [] # Number numbers
p = [] # Prime numbers
yes = ["yes", "y", "yeah", "yee", "si", "da", "alright", "sure", "8)", "affirmative", "yeh", "postive"] #Stuff that means "yes"
no = ["no", "n", "nah", "nope", "negatory", "negative", "not", "go away", "ain't"] #Stuff that means "no"
checkingTen = True #Are we looking for input from the user to know what power of ten to use?
divfreq = 25

#Defines n.
while x < powerTen:
	x += 1
	n.append(x)

#IS IT A YES OR A NO, HUH?!!??
def isyes(inp, yes, no):
	inp = inp.lower()
	if inp in yes:
		print("Selected: [YES]")
		return(True)
	elif inp in no:
		print("Selected: [NO]")
		return(False)
	else:
		print("Unknown input, considering as 'No'")
		return(False)

#Create divider line
def separ():
	for i in range(0,80):
		print("-", end = "")

"""INTRODUCICITATIONATION"""

#Hello world!
separ()
print("Welcome to J&E's prime number finder.")
separ()

#How big do you want it world?
print("At what power of ten should the calculation cut off?")
print("--Warning: Numbers above 5 will take a long time--")
while checkingTen:
	try:
		power = input()
		power = int(power)
		quantity = 10 ** power
		checkingTen = False
	except:
		print("Please input a number")
separ()

#And now world, we do magic
n = list(range(2, quantity))

"""Sweet, sweet math (or maths if you are british)"""

#Start timer
start = time.time()

#Core Program. #YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE (eric is confused because he is too dumb to understand this :())
while 0 < len(n):
	x = n.pop(0)
	p.append(x)
	y = 0
	while y < len(n):
		if n[y] % x == 0:
			del n[y]
		else:
			y += 1
#Eric is still confused even after reading it a few times

#Time elapsed
end = time.time()
print("Time elapsed:")
elapsed = round(end - start, 3)
print(str(elapsed) + " seconds.")

"""The grand climax/conclusion whatever thing"""

#Printing stuff (not with a printer ofc)
separ()
print("There are %s prime numbers under %s." % (len(p), quantity))

#Want to print?
separ()
print("Do you want to print the prime numbers found ? It may crash the console (y/n)")
print("-------------Hey, you may not want to do this. It lags. A lot.-------------")
if isyes(input(), yes, no):
	print(p)

#Want to print to file? And then possibly print 4 real?
separ()
print("Would you like to save the numbers to a file?")
if isyes(input(), yes, no):
	filename = str(quantity) + ".txt"
	f = open(filename, 'w')
	f.write("This file was generated by: J&Es Prime finder \n")
	print("Saved to: ", filename )
	today = datetime.date.today()
	f.write("Timestamp: %s \n" % (today))
	f.write("Time elapsed: %s seconds. \n" % (elapsed))
	f.write("There are %s prime numbers under %s. \n" % (len(p), quantity))
	f.write("Prime numbers under %s: \n" % (quantity))
	for item in p:
		f.write(str(item) +", ")
		if p.index(item) % divfreq == 0:
			f.write("\n")
	f.close()

#Farewell
separ()
print("Program made by Jalil with assistance from Eric")
print("Have a good day!")
separ()
